var searchData=
[
  ['get_5fdifferential_5fblocks',['get_differential_blocks',['../class_interface.html#ae85c272b0b3c7cfcbe8ddea87a769fd9',1,'Interface']]],
  ['get_5fface_5fflags',['get_face_flags',['../class_interface.html#acf2774b381333552b748390837047290',1,'Interface']]],
  ['get_5fjacobian_5fflags',['get_jacobian_flags',['../class_interface.html#a5d683a45b4d023ac92deabaeed47be3d',1,'Interface']]],
  ['get_5fjacobian_5fpreconditioner_5fflags',['get_jacobian_preconditioner_flags',['../class_interface.html#a5d6143b8a0527b21927e7851dacf3d74',1,'Interface']]],
  ['get_5fmapping',['get_mapping',['../class_interface.html#aa11a73af702dc7a07c436a7aadd290f1',1,'Interface']]],
  ['get_5fpreconditioner_5fenergy',['get_preconditioner_energy',['../class_conservative_interface.html#a1db532fd05049be1561a2b80330cbffc',1,'ConservativeInterface::get_preconditioner_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;c, Scratch &amp;s, CopySystem &amp;d, Sdouble &amp;e) const '],['../class_conservative_interface.html#a6ad8bab8a51f98124f2969e483856a26',1,'ConservativeInterface::get_preconditioner_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;c, Scratch &amp;s, CopyPreconditioner &amp;d, SSdouble &amp;e) const '],['../class_interface.html#a098a3c2c533b1ad5d69381ae60e6eb01',1,'Interface::get_preconditioner_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;, Scratch &amp;, CopySystem &amp;, Sdouble &amp;) const '],['../class_interface.html#ad3cf12aaae0259f00043d8e1ff3d05bb',1,'Interface::get_preconditioner_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;, Scratch &amp;, CopyPreconditioner &amp;, SSdouble &amp;) const ']]],
  ['get_5fpreconditioner_5fresidual',['get_preconditioner_residual',['../class_interface.html#a67b0bc48c6547b602da20dba82b40a55',1,'Interface::get_preconditioner_residual()'],['../class_non_conservative_interface.html#af19e24930397cbb12bedd86c07b29961',1,'NonConservativeInterface::get_preconditioner_residual()']]],
  ['get_5fresidual_5fflags',['get_residual_flags',['../class_interface.html#a45479e47ba3bfe33423649b6cf21ccff',1,'Interface']]],
  ['get_5fsystem_5fenergy',['get_system_energy',['../class_conservative_interface.html#aa5e0b9f01d755cb20428f27b108ca9ab',1,'ConservativeInterface::get_system_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;c, Scratch &amp;s, CopySystem &amp;d, Sdouble &amp;e) const '],['../class_conservative_interface.html#ad28b7f2ced196ca1a59b278fdaefcae8',1,'ConservativeInterface::get_system_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;c, Scratch &amp;s, CopySystem &amp;d, SSdouble &amp;e) const '],['../class_interface.html#a2d9128b2bbad5964abe5178d6fe7f17c',1,'Interface::get_system_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;, Scratch &amp;, CopySystem &amp;, Sdouble &amp;) const '],['../class_interface.html#aed5f638f41221c3da988b5bb3e2d13ce',1,'Interface::get_system_energy(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;, Scratch &amp;, CopySystem &amp;, SSdouble &amp;) const ']]],
  ['get_5fsystem_5fresidual',['get_system_residual',['../class_interface.html#ac9c94808fa675095b8ed0e423c9aaadf',1,'Interface::get_system_residual(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;cell, Scratch &amp;scratch, CopySystem &amp;data, std::vector&lt; Sdouble &gt; &amp;local_residual) const '],['../class_interface.html#a5bc373809cd2fb64f2880b8ec1216b2e',1,'Interface::get_system_residual(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;cell, Scratch &amp;scratch, CopySystem &amp;data, std::vector&lt; double &gt; &amp;local_residual) const '],['../class_non_conservative_interface.html#a82c490b2290907dc572f1c1979a17ac4',1,'NonConservativeInterface::get_system_residual(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;cell, Scratch &amp;scratch, CopySystem &amp;data, std::vector&lt; double &gt; &amp;local_residual) const '],['../class_non_conservative_interface.html#adcf9edffbb4af551b7a18bd846b06614',1,'NonConservativeInterface::get_system_residual(const typename DoFHandler&lt; dim, spacedim &gt;::active_cell_iterator &amp;cell, Scratch &amp;scratch, CopySystem &amp;data, std::vector&lt; Sdouble &gt; &amp;local_residual) const ']]],
  ['ghosted',['ghosted',['../class_scoped_l_a_c_initializer.html#a7d6847b680dbba593cdbf768356cfe44',1,'ScopedLACInitializer::ghosted(TrilinosWrappers::MPI::BlockVector &amp;v, bool fast=false)'],['../class_scoped_l_a_c_initializer.html#a7b651625fa3017b650126038271e46bb',1,'ScopedLACInitializer::ghosted(BlockVector&lt; double &gt; &amp;, bool fast=false)']]]
];
